Desktop version
summyalena/Website-Portfolio pull request #4
Opened 2022-07-08 02:04 UTC by summyalena

Hello Microverse, 
1. I created the desktop version of my portfolio and implemented media queries.
2. I added more css stylings

2022-07-08 03:19 UTC, muneebulrehman requested changes
Hi @summyalena , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 03:19 UTC, muneebulrehman commented on index.css
> +@media screen and (min-width: 769px) {
Your navbar is not matching the Figma template of your choosing. Kindly fix it. 
| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/33268927/177908594-efc5f9c0-a77b-4ab7-9431-c5728993b07f.png) | ![image](https://user-images.githubusercontent.com/33268927/177908653-fb00db9d-64e5-4bd1-87d1-1f2d853872ae.png) |

2022-07-08 03:19 UTC, muneebulrehman commented on index.css
> +@media screen and (min-width: 769px) {
Your header section layout also does not match the Figma template. Kindly fix it. Consider using the same font size, font weight, padding and margins as in the Figma template.
| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/33268927/177908878-3bd7c4ab-c6a2-4394-adaa-ff6340283dd7.png) | ![image](https://user-images.githubusercontent.com/33268927/177908930-a9e235d9-e7a1-46e5-973c-1ffea12d3252.png) |

2022-07-08 03:19 UTC, muneebulrehman commented on index.css
> +@media screen and (min-width: 769px) {
Your work section headline is also not displaying as per the Figma template. Consider fixing it.
| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/33268927/177909342-37adc113-dac2-411d-a638-da9412e32443.png) | ![image](https://user-images.githubusercontent.com/33268927/177909399-dc3ca4da-aadd-4f40-81e0-9cc37b971be0.png) |

2022-07-08 03:19 UTC, muneebulrehman commented on index.css
> +@media screen and (min-width: 769px) {
The layout of your main work section is also not as per the Figma template. Consider fixing it.
| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/33268927/177909601-0f4e19ef-d1f4-4d32-9efa-eb81b5032f61.png) | ![image](https://user-images.githubusercontent.com/33268927/177909663-cce50b6b-34f7-48e0-ab6f-feb267c80b3f.png) |

2022-07-08 03:19 UTC, muneebulrehman commented on index.css
> +@media screen and (min-width: 769px) {
Your about section also does not match the Figma template of your choosing. Kindly fix it. Please use the same padding and margins as in the Figma design.
| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/33268927/177909884-9a8acd4d-5149-4454-83ce-fdac1b013a2b.png) ![image](https://user-images.githubusercontent.com/33268927/177909967-99860101-4bff-4893-866b-7b5b8f4ad979.png) | ![image](https://user-images.githubusercontent.com/33268927/177909831-379819bc-8cfa-40e7-9c11-d9a6ee6164ac.png) |

2022-07-08 03:19 UTC, muneebulrehman commented on index.css
> +@media screen and (min-width: 769px) {
Your contact-me section layout is also not as per the Figma template. Please use the same margins, and padding and follow the layout of the Figma template.
| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/33268927/177910261-a91eaab1-fc89-48f3-b15a-5ae8f8848198.png) | ![image](https://user-images.githubusercontent.com/33268927/177910306-7f8f813a-78dc-4bb2-bb04-00770c140b99.png) |

2022-07-08 22:00 UTC, BertrandConxy requested changes
Hi @summyalena ✋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🏃

 ## Highlights 💪 
- NO linter errors
- Descriptive PR
- Great effort in making improvements based on the reviews
- project works fine on my pc

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 22:00 UTC, BertrandConxy commented on index.css
> +  }
- [ ] I selected these CSS codes but I wanted to talk about the HTML codes they are representing. When you look at your nav list items, you will find out that there is only an envelope icon image and that is the reason why there are no links that are appearing on your page as the previous reviewer said, you have to build those links (namely: Portfolio, About, Contact). **so please write codes for their HTML, make sure that they are links and each is a list item just like that envelope image icon** 😃

**Your current navigation still not having the nav links**
![](https://user-images.githubusercontent.com/33268927/177908594-efc5f9c0-a77b-4ab7-9431-c5728993b07f.png)

2022-07-08 22:00 UTC, BertrandConxy commented on index.css
> +
- [ ] [OPTIONAL] Your project cards are supposed to have the hover interaction effect. Initially, all your project cards should have that overlay effect with the project description text (you can see how cardwork2 and 3 look) and then, **when the user hovers on each of them, it should have the styles like the ones you have put on the project card 1(cardwork1).** That means the user should be able to see the `See project` button and the project image only. Please try to work on that.

2022-07-09 00:02 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @summyalena ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Professional Readme ✔️
- Professional Pull request ✔️
- Linters are passing ✔️

## Optional suggestions
- I would have added inline comments but it was not possible because of the files that were previously changed🙏

- [ ] [Optional] You may please remove the black line from your footer section. It does not actually exist in the Figma design
![black footer](https://user-images.githubusercontent.com/63917725/178082021-e11e7961-6bd8-44ab-a862-d60cb804a841.PNG)

- [ ] [Optional] You may please implement the hover effect correctly on the button of your first card.

##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-09 00:02 UTC, 1GORDON commented on index.css
> +  }
Hello @summyalena ✋

- [ ] [Optional] You may have to add a margin-bottom on your first page. This makes your difer from the design provided in the Figma template.
- Your design
![page1](https://user-images.githubusercontent.com/63917725/178082525-288ae12d-68e5-4195-b1ad-9c9e3f6938d5.PNG)

- Figma design
![Figma design](https://user-images.githubusercontent.com/63917725/178082547-3207b2ab-3bfd-4632-b463-794478b8c75a.PNG)

2022-07-09 00:02 UTC, 1GORDON commented on index.css
> +  }
Great job @summyalena 🤝

- [ ] [Optional] You may please make your design more responsive so that some elements won't overlap others on smaller screens.
![responsive1](https://user-images.githubusercontent.com/63917725/178082719-d39e2c0a-f5bc-40c1-a278-75fc3de930a1.PNG)

![responsive2](https://user-images.githubusercontent.com/63917725/178082764-b699d021-fb47-4a2a-bf29-a66ee8124c73.PNG)

2022-07-09 00:02 UTC, 1GORDON commented on index.css
> +  }
Great job @summyalena 🤝

- [ ] [Optional] You may kindly try to make the technologies in your design similar to the ones on the Figma template
- Your design
![your tech](https://user-images.githubusercontent.com/63917725/178083141-98b8fb0b-aecf-4f16-a8f1-1f5c0f71110c.PNG)

- Figma design
![figma tech](https://user-images.githubusercontent.com/63917725/178083188-c1554625-b3c9-4446-8b33-e087235a756a.PNG)

2022-07-09 08:08 UTC, summyalena commented on index.css
> +  }
Okay Mr Gordon. Thank you.

2022-07-09 08:08 UTC, merged